### ISSUE TITLE
min relay fee not met, 195 < 196

### ISSUE THREAD

**Issue by DanGould** [chaincase-app/nolooking#34]
Our fee calculation is probably wrong, not Sparrow's. We hit this issue on a dual-channel opening.

The issue is likely here: https://github.com/chaincase-app/nolooking/blob/919dc3cd4593a48d1ada410d469579b4ef1bbb8f/src/scheduler.rs#L348-L360

```
	at javafx.graphics@18/javafx.concurrent.Service.lambda$executeTask$7(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
2022-10-28 05:03:12,464 ERROR Error broadcasting transaction
com.sparrowwallet.sparrow.net.ServerException: the transaction was rejected by network rules.

min relay fee not met, 195 < 196
[020000000001011e58d18bf75d1d392b5563ad2313f9f6d09a8ca4e83bca0447f5334d7c385ffe0000000000fdffffff03445f080000000000160014ae75c6152e82bd987b97dbdf39740121670162bd400d030000000000220020dcbbd29ab4983c93be31cfbcd30fd5533e5467c83de4420f4343e0ef66c54d7978d40300000000002200204d459ec73acfd818c991d31bd2985eedfe5aa81cb3207277db064bf0fcb1cd84024730440220217e5a5b1240184c0e205e2b5ebc33f0c8930e92e234ca62686cb2058fa5fce40220385c984977f733a6a79650ff54a6566be0777740a3f567947c93783ef1b86e0c01210363fb690738f1c941b66b108b5a2e80e7f3d6a551a457e4270aa231ea4ed60c21e19a0b00]
	at com.sparrowwallet.sparrow@1.7.0/com.sparrowwallet.sparrow.net.ElectrumServer.broadcastTransaction(Unknown Source)
	at com.sparrowwallet.sparrow@1.7.0/com.sparrowwallet.sparrow.net.ElectrumServer.broadcastTransactionPrivately(Unknown Source)
	at com.sparrowwallet.sparrow@1.7.0/com.sparrowwallet.sparrow.net.ElectrumServer$BroadcastTransactionService$1.call(Unknown Source)
	at com.sparrowwallet.sparrow@1.7.0/com.sparrowwallet.sparrow.net.ElectrumServer$BroadcastTransactionService$1.call(Unknown Source)
	at javafx.graphics@18/javafx.concurrent.Task$TaskCallable.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at javafx.graphics@18/javafx.concurrent.Service.lambda$executeTask$6(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at javafx.graphics@18/javafx.concurrent.Service.lambda$executeTask$7(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: com.sparrowwallet.sparrow.net.ElectrumServerRpcException: the transaction was rejected by network rules.
```

**Comment by nickfarrow** [comment]
Can we hack around this one? Just -1? It's pretty severe given everyone defaults to 1sat/vB and sparrow is our best wallet.

**Comment by DanGould** [comment]
Are you also running into this issue?

**Comment by nickfarrow** [comment]
I did a few weeks back but I now just go like 5 sats per byte on nolooking and then 2sat/vB for sender, I think i was getting this issue when I was doing max of 1 and sender feerate of 1
